services:
  db:
    container_name: my_planner_dev_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    container_name: my_planner_dev_keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev # Use this for development
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data

  loki:
    container_name: my_planner_dev_loki
    image: grafana/loki:latest
    networks:
      - 'grafana_network'
    ports:
      - '3100:3100'
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    container_name: my_planner_dev_grafana
    image: grafana/grafana:latest
    networks:
      - 'grafana_network'
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    depends_on:
      - loki

volumes:
  postgres_data:
  keycloak_data:
  loki_data:
  grafana_data:

networks:
  grafana_network:
    driver: bridge
